### ISSUE TITLE
Visual Studio 2019 Compile Errors

### ISSUE THREAD

**Issue by pixelblender** [cmuparlay/concurrent_deferred_rc#1]
Hi,

As the title says, I can't compile the project on VS2019.

**Comment by DanielLiamAnderson** [comment]
Could you please share some more information?

* What version of VS2019 are you using?
* Were you compiling the tests & benchmarks, or your own project linked with ours?
* Could you share the output of running CMake?
* Could you share the compile error?

**Comment by DanielLiamAnderson** [comment]
As of Version #2 of the library, it now correctly compiles on Windows.
